[package]
name = "constant-multiplication-generator"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lz4_flex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
unsigned-varint.workspace = true
