[package]
name = "constant_multiplication"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
bincode.workspace = true
serde.workspace = true
lz4_flex.workspace = true

[lib]
name = "constant_multiplication"
crate-type = ["cdylib"]
